import { useState, useRef, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { User, Camera, Fingerprint, Eye, CheckCircle, AlertCircle } from 'lucide-react';
import api from '../services/api';

const Register = () => {
  const [currentStep, setCurrentStep] = useState(1);
  const [formData, setFormData] = useState({
    studentId: '',
    name: '',
    email: '',
    password: '',
    department: '',
    role: 'student'
  });
  const [biometricData, setBiometricData] = useState({
    faceImage: null,
    faceEmbedding: null,
    fingerprintData: null
  });
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [cameraActive, setCameraActive] = useState(false);
  const videoRef = useRef(null);
  const canvasRef = useRef(null);
  const navigate = useNavigate();

  // Cleanup camera when component unmounts or step changes
  useEffect(() => {
    return () => {
      // Always stop camera when component unmounts
      if (videoRef.current?.srcObject) {
        const tracks = videoRef.current.srcObject.getTracks();
        tracks.forEach(track => {
          console.log('Cleanup: Stopping camera track:', track.label);
          track.stop();
        });
        videoRef.current.srcObject = null;
      }
    };
  }, []);

  // Stop camera when leaving face enrollment step
  useEffect(() => {
    if (currentStep !== 2 && cameraActive) {
      console.log('Step changed, stopping camera');
      stopCamera();
    }
  }, [currentStep, cameraActive]);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
  };

  const startCamera = async () => {
    console.log('=== STARTING CAMERA IN REGISTER ===');
    try {
      // Stop any existing stream
      if (videoRef.current?.srcObject) {
        const tracks = videoRef.current.srcObject.getTracks();
        tracks.forEach(track => track.stop());
        videoRef.current.srcObject = null;
      }

      console.log('1. Requesting camera...');
      const stream = await navigator.mediaDevices.getUserMedia({ 
        video: true,
        audio: false
      });
      
      console.log('2. Got stream:', stream);
      
      if (videoRef.current) {
        console.log('3. Setting video source...');
        videoRef.current.srcObject = stream;
        
        // Wait for video to load and then play
        videoRef.current.onloadedmetadata = () => {
          console.log('4. Video metadata loaded');
          videoRef.current.play().then(() => {
            console.log('5. Video playing successfully!');
            setCameraActive(true);
          }).catch(error => {
            console.error('Play error:', error);
            setError('Failed to start video playback');
          });
        };
      }
    } catch (error) {
      console.error('Camera error:', error);
      setError('Camera access denied. Please allow camera access to continue.');
    }
  };

  const stopCamera = () => {
    console.log('=== STOPPING CAMERA ===');
    if (videoRef.current?.srcObject) {
      const tracks = videoRef.current.srcObject.getTracks();
      tracks.forEach(track => {
        console.log('Stopping track:', track.label);
        track.stop();
      });
      videoRef.current.srcObject = null;
      setCameraActive(false);
    }
  };

  const capturePhoto = () => {
    if (videoRef.current && canvasRef.current) {
      const canvas = canvasRef.current;
      const video = videoRef.current;
      const context = canvas.getContext('2d');
      
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      context.drawImage(video, 0, 0);
      
      const imageData = canvas.toDataURL('image/jpeg', 0.8);
      setBiometricData(prev => ({
        ...prev,
        faceImage: imageData,
        faceEmbedding: generateMockEmbedding() // In real app, this would be AI-generated
      }));
      
      stopCamera();
      setCurrentStep(3);
    }
  };

  const generateMockEmbedding = () => {
    // Mock face embedding - in real app, this would be generated by AI
    return Array.from({length: 128}, () => Math.random());
  };

  const simulateFingerprint = async () => {
    setLoading(true);
    // Simulate fingerprint capture
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    setBiometricData(prev => ({
      ...prev,
      fingerprintData: {
        template: Array.from({length: 256}, () => Math.random()),
        quality: 95,
        timestamp: new Date().toISOString()
      }
    }));
    
    setLoading(false);
    setCurrentStep(4);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      // First register the user
      const response = await api.post('/auth/register', formData);
      
      if (response.data.success) {
        // Then save biometric data
        const biometricResponse = await api.post('/auth/save-biometrics', {
          userId: response.data.data.id,
          faceImage: biometricData.faceImage,
          faceEmbedding: biometricData.faceEmbedding,
          fingerprintData: biometricData.fingerprintData
        });
        
        alert('Registration successful with biometric enrollment! Please login.');
        navigate('/login');
      }
    } catch (err) {
      setError(err.response?.data?.message || 'Registration failed. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const BasicInfoStep = () => (
    <div className="space-y-4">
      <h2 className="text-2xl font-bold text-gray-900 mb-6">Create Account</h2>

      {error && (
        <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg mb-4">
          <div className="flex items-center gap-2">
            <AlertCircle className="w-5 h-5" />
            <span>{error}</span>
          </div>
        </div>
      )}

      <div>
        <label className="block text-gray-700 text-sm font-semibold mb-2">
          Student/Faculty ID
        </label>
        <input
          type="text"
          name="studentId"
          placeholder="e.g., STU001"
          value={formData.studentId}
          onChange={handleChange}
          className="w-full px-4 py-3 border-2 border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-gray-900 bg-white"
          required
        />
      </div>

      <div>
        <label className="block text-gray-700 text-sm font-semibold mb-2">
          Full Name
        </label>
        <input
          type="text"
          name="name"
          placeholder="Enter your full name"
          value={formData.name}
          onChange={handleChange}
          className="w-full px-4 py-3 border-2 border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-gray-900 bg-white"
          required
        />
      </div>

      <div>
        <label className="block text-gray-700 text-sm font-semibold mb-2">
          Email
        </label>
        <input
          type="email"
          name="email"
          placeholder="Enter your email"
          value={formData.email}
          onChange={handleChange}
          className="w-full px-4 py-3 border-2 border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-gray-900 bg-white"
          required
        />
      </div>

      <div>
        <label className="block text-gray-700 text-sm font-semibold mb-2">
          Password
        </label>
        <input
          type="password"
          name="password"
          placeholder="••••••••"
          value={formData.password}
          onChange={handleChange}
          className="w-full px-4 py-3 border-2 border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-gray-900 bg-white"
          required
          minLength={6}
        />
      </div>

      <div>
        <label className="block text-gray-700 text-sm font-semibold mb-2">
          Department
        </label>
        <input
          type="text"
          name="department"
          placeholder="e.g., Computer Science"
          value={formData.department}
          onChange={handleChange}
          className="w-full px-4 py-3 border-2 border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-gray-900 bg-white"
          required
        />
      </div>

      <div>
        <label className="block text-gray-700 text-sm font-semibold mb-2">
          Role
        </label>
        <select
          name="role"
          value={formData.role}
          onChange={handleChange}
          className="w-full px-4 py-3 border-2 border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-gray-900 bg-white"
        >
          <option value="student">Student</option>
          <option value="faculty">Faculty</option>
          <option value="admin">Admin</option>
        </select>
      </div>

      <button
        type="button"
        onClick={() => setCurrentStep(2)}
        className="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 px-4 rounded-lg transition duration-200"
      >
        Continue to Biometric Setup
      </button>
    </div>
  );

  const FaceEnrollmentStep = () => (
    <div className="space-y-6">
      <div className="text-center">
        <Camera className="w-12 h-12 text-blue-600 mx-auto mb-4" />
        <h2 className="text-2xl font-bold text-gray-900 mb-2">Face Enrollment</h2>
        <p className="text-gray-600">We'll capture your face for secure attendance verification</p>
      </div>

      <div className="relative bg-black rounded-lg overflow-hidden">
        <video
          ref={videoRef}
          autoPlay
          playsInline
          muted
          style={{
            width: '100%',
            height: '320px',
            backgroundColor: '#000',
            objectFit: 'cover',
            transform: 'scaleX(-1)' // Mirror for better user experience
          }}
        />
        <canvas ref={canvasRef} className="hidden" />
        
        {!cameraActive && (
          <div className="absolute inset-0 flex items-center justify-center bg-gray-800">
            <div className="text-center text-white">
              <Camera className="w-16 h-16 mx-auto mb-4 opacity-50" />
              <p>Camera not active</p>
            </div>
          </div>
        )}

        {cameraActive && (
          <div className="absolute inset-0 flex items-center justify-center">
            <div className="w-48 h-64 border-4 border-white rounded-full opacity-70">
              <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2">
                <Eye className="w-8 h-8 text-white" />
              </div>
            </div>
          </div>
        )}
      </div>

      <div className="flex gap-4">
        {!cameraActive ? (
          <button
            onClick={startCamera}
            className="flex-1 bg-blue-600 hover:bg-blue-700 text-white py-3 px-6 rounded-lg font-semibold flex items-center justify-center gap-2 transition"
          >
            <Camera className="w-5 h-5" />
            Start Camera
          </button>
        ) : (
          <>
            <button
              onClick={capturePhoto}
              className="flex-1 bg-green-600 hover:bg-green-700 text-white py-3 px-6 rounded-lg font-semibold flex items-center justify-center gap-2 transition"
            >
              <CheckCircle className="w-5 h-5" />
              Capture Photo
            </button>
            <button
              onClick={stopCamera}
              className="px-6 py-3 bg-gray-600 hover:bg-gray-700 text-white rounded-lg font-semibold transition"
            >
              Cancel
            </button>
          </>
        )}
      </div>

      <button
        onClick={() => setCurrentStep(1)}
        className="w-full bg-gray-300 hover:bg-gray-400 text-gray-700 py-2 px-4 rounded-lg font-medium transition"
      >
        Back to Basic Info
      </button>
    </div>
  );

  const FingerprintEnrollmentStep = () => (
    <div className="space-y-6">
      <div className="text-center">
        <Fingerprint className="w-12 h-12 text-blue-600 mx-auto mb-4" />
        <h2 className="text-2xl font-bold text-gray-900 mb-2">Fingerprint Enrollment</h2>
        <p className="text-gray-600">Place your finger on the scanner to complete enrollment</p>
      </div>

      <div className="relative">
        <div className="w-32 h-32 mx-auto bg-gradient-to-br from-blue-500 to-purple-600 rounded-full flex items-center justify-center shadow-lg">
          <div className={`w-24 h-24 bg-white rounded-full flex items-center justify-center transition-all duration-300 ${
            loading ? 'animate-pulse' : ''
          }`}>
            <Fingerprint className="w-12 h-12 text-blue-600" />
          </div>
        </div>

        {loading && (
          <div className="absolute inset-0 flex items-center justify-center">
            <div className="w-36 h-36 border-4 border-blue-200 border-t-blue-600 rounded-full animate-spin" />
          </div>
        )}
      </div>

      <button
        onClick={simulateFingerprint}
        disabled={loading}
        className="w-full bg-purple-600 hover:bg-purple-700 disabled:bg-gray-400 text-white py-3 px-6 rounded-lg font-semibold flex items-center justify-center gap-2 transition"
      >
        {loading ? (
          <>
            <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white" />
            Scanning Fingerprint...
          </>
        ) : (
          <>
            <Fingerprint className="w-5 h-5" />
            Scan Fingerprint
          </>
        )}
      </button>

      <button
        onClick={() => setCurrentStep(2)}
        className="w-full bg-gray-300 hover:bg-gray-400 text-gray-700 py-2 px-4 rounded-lg font-medium transition"
      >
        Back to Face Enrollment
      </button>
    </div>
  );

  const CompletionStep = () => (
    <div className="space-y-6 text-center">
      <div className="w-24 h-24 bg-green-500 rounded-full flex items-center justify-center mx-auto animate-bounce">
        <CheckCircle className="w-12 h-12 text-white" />
      </div>
      
      <div>
        <h2 className="text-3xl font-bold text-green-600 mb-2">Enrollment Complete!</h2>
        <p className="text-gray-600">Your biometric data has been securely captured</p>
      </div>

      <div className="bg-green-50 border border-green-200 rounded-lg p-6">
        <div className="space-y-3 text-left">
          <div className="flex items-center justify-between">
            <span className="text-gray-600">Face Recognition:</span>
            <span className="flex items-center gap-2 text-green-600 font-semibold">
              <CheckCircle className="w-4 h-4" />
              Enrolled
            </span>
          </div>
          <div className="flex items-center justify-between">
            <span className="text-gray-600">Fingerprint:</span>
            <span className="flex items-center gap-2 text-green-600 font-semibold">
              <CheckCircle className="w-4 h-4" />
              Enrolled
            </span>
          </div>
          <div className="flex items-center justify-between">
            <span className="text-gray-600">Security Level:</span>
            <span className="font-semibold text-blue-600">High</span>
          </div>
        </div>
      </div>

      <button
        onClick={handleSubmit}
        disabled={loading}
        className="w-full bg-blue-600 hover:bg-blue-700 disabled:bg-gray-400 text-white py-3 px-6 rounded-lg font-semibold transition"
      >
        {loading ? 'Creating Account...' : 'Complete Registration'}
      </button>
    </div>
  );

  const ProgressBar = () => (
    <div className="mb-8">
      <div className="flex items-center justify-between mb-2">
        {[1, 2, 3, 4].map((step) => (
          <div key={step} className="flex items-center">
            <div className={`w-10 h-10 rounded-full flex items-center justify-center font-semibold ${
              currentStep > step 
                ? 'bg-green-500 text-white' 
                : currentStep === step 
                ? 'bg-blue-600 text-white' 
                : 'bg-gray-200 text-gray-500'
            }`}>
              {currentStep > step ? <CheckCircle className="w-5 h-5" /> : step}
            </div>
            {step < 4 && (
              <div className={`w-16 h-1 mx-2 ${
                currentStep > step ? 'bg-green-500' : 'bg-gray-200'
              }`} />
            )}
          </div>
        ))}
      </div>
      <div className="flex justify-between text-xs text-gray-600">
        <span>Basic Info</span>
        <span>Face Scan</span>
        <span>Fingerprint</span>
        <span>Complete</span>
      </div>
    </div>
  );

  return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
      <div className="w-full max-w-md">
        {/* Header */}
        <div className="bg-blue-600 text-white p-4 rounded-t-xl flex items-center gap-2">
          <div className="w-8 h-8 bg-white rounded-full flex items-center justify-center">
            <User className="w-5 h-5 text-blue-600" />
          </div>
          <span className="font-semibold text-lg">Smart Attendance</span>
        </div>

        {/* Registration Form */}
        <div className="bg-white p-8 rounded-b-xl shadow-lg">
          <ProgressBar />

          {currentStep === 1 && <BasicInfoStep />}
          {currentStep === 2 && <FaceEnrollmentStep />}
          {currentStep === 3 && <FingerprintEnrollmentStep />}
          {currentStep === 4 && <CompletionStep />}

          <div className="mt-6 text-center text-gray-600">
            <span className="text-sm">Already have an account? </span>
            <Link to="/login" className="text-blue-600 hover:text-blue-700 font-medium text-sm">
              Login →
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Register;
